services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=divance
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: